### ISSUE TITLE
performance/performance_models.md

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow-docs#10]
* Markdown 文件：[文件地址](https://github.com/xitu/tensorflow-docs/blob/zh-hans/performance/performance_models.md)
  * PR 地址：#56
  **注意**：一个 `pull request` 中需要翻译完并提交对应 `Issue` 中指定的所有文件
  ----
  * 翻译时间：10 天
  * 校对时间：3 天
  * 翻译积分：10 分
  * 校对积分：3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by witmax** [comment]
@leviding 认领翻译

**Comment by fanyijihua** [comment]
@witmax 好的呢 👍

**Comment by leviding** [comment]
@witmax 翻译的怎么样啦

**Comment by leviding** [comment]
@witmax 翻译的怎么样了

**Comment by witmax** [comment]
@leviding 翻译完成 https://github.com/xitu/tensorflow-docs/pull/56
