### ISSUE TITLE
tutorials/estimators/linear.ipynb, tutorials/estimators/linear.md, tutorials/keras/basic_classification.ipynb, tutorials/keras/basic_classification.md, tutorials/keras/basic_regression.ipynb, tutorials/keras/basic_regression.md  and tutorials/estimators/cnn.md

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow-docs#108]
* Markdown 文件：
    * [x] [tutorials/estimators/cnn.md](https://github.com/xitu/tensorflow-docs/blob/zh-hans/tutorials/estimators/cnn.md)
    * [x] [tutorials/estimators/linear.ipynb](https://github.com/xitu/tensorflow-docs/blob/zh-hans/tutorials/estimators/linear.ipynb)
    * [x] [tutorials/estimators/linear.md](https://github.com/xitu/tensorflow-docs/blob/zh-hans/tutorials/estimators/linear.md)
    * [x] [tutorials/keras/basic_classification.ipynb](https://github.com/xitu/tensorflow-docs/blob/zh-hans/tutorials/keras/basic_classification.ipynb)
    * [x] [tutorials/keras/basic_classification.md](https://github.com/xitu/tensorflow-docs/blob/zh-hans/tutorials/keras/basic_classification.md)
    * [x] [tutorials/keras/basic_regression.ipynb](https://github.com/xitu/tensorflow-docs/blob/zh-hans/tutorials/keras/basic_regression.ipynb)
    * [x] [tutorials/keras/basic_regression.md](https://github.com/xitu/tensorflow-docs/blob/zh-hans/tutorials/keras/basic_regression.md)
  * PR 地址：
    * [x] #111 
    * [x] #138 
    * [x] #144 
  **注意**：这些内容可以根据你自己的安排，分多个 PR 提交。
  ----
  * 翻译时间：15 天
  * 校对时间：4 天
  * 翻译积分：15 分
  * 校对积分：4-7 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
由 @lsvih 翻译

**Comment by leviding** [comment]
@lsvih 最近在忙吧，忙完了记得来翻译哈，不急，按你的时间来 😄

**Comment by lsvih** [comment]
@leviding 忘了，近期做完

**Comment by leviding** [comment]
记得这个哈

**Comment by leviding** [comment]
@lsvih 翻译的怎么样啦

**Comment by lsvih** [comment]
陆续将剩下的上传

**Comment by leviding** [comment]
@lsvih 这篇还有两个，对吧

**Comment by lsvih** [comment]
@leviding 对，估计明天完成

**Comment by leviding** [comment]
一个大部头完成！辛苦啦 👍
