### ISSUE TITLE
performance/xla/operation_semantics.md

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow-docs#11]
* Markdown 文件：[文件地址](https://github.com/xitu/tensorflow-docs/blob/zh-hans/performance/xla/operation_semantics.md)
  * PR 地址：
  **注意**：一个 `pull request` 中需要翻译完并提交对应 `Issue` 中指定的所有文件
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：5 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by pkuwwt** [comment]
申请翻译 @LeviDing

**Comment by leviding** [comment]
@pkuwwt ok，辛苦了

**Comment by leviding** [comment]
@pkuwwt 这个文件有空弄下吧

**Comment by pkuwwt** [comment]
@leviding 忘了说了，早翻译完了

**Comment by leviding** [comment]
@pkuwwt 好的
