### ISSUE TITLE
install/source.md, guide/index.md, guide/autograph.ipynb and guide/datasets.md

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow-docs#115]
* Markdown 文件：
    * [x] [guide/datasets.md](https://github.com/xitu/tensorflow-docs/blob/zh-hans/guide/datasets.md)
    * [x] [guide/index.md](https://github.com/xitu/tensorflow-docs/blob/zh-hans/guide/index.md)
    * [x] [install/source.md](https://github.com/xitu/tensorflow-docs/blob/zh-hans/install/source.md)
    * [x] [guide/autograph.ipynb](https://github.com/xitu/tensorflow-docs/blob/zh-hans/guide/autograph.ipynb)
  * PR 地址：
    * [x] [https://github.com/xitu/tensorflow-docs/pull/116](https://github.com/xitu/tensorflow-docs/pull/116)
    * [x] [https://github.com/xitu/tensorflow-docs/pull/117](https://github.com/xitu/tensorflow-docs/pull/117)
    * [x] [https://github.com/xitu/tensorflow-docs/pull/118](https://github.com/xitu/tensorflow-docs/pull/118)

  **注意**：这些内容以几个 PR 提交均可，看你的安排。
  ----
  * 翻译时间：10 天
  * 校对时间：3 天
  * 翻译积分：11-13 分
  * 校对积分：3-6 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
由 @zhusimaji 翻译

**Comment by leviding** [comment]
@zhusimaji 还差一个 [guide/autograph.ipynb](guide/autograph.ipynb) 对啵~

**Comment by zhusimaji** [comment]
@leviding  全部翻译结束

**Comment by zhusimaji** [comment]
@leviding 赶在最后一晚完成了，下次多一点预算时间出来 :beers:
