### ISSUE TITLE
programmers_guide/low_level_intro.md

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow-docs#12]
* Markdown 文件：[文件地址](https://github.com/xitu/tensorflow-docs/blob/zh-hans/programmers_guide/low_level_intro.md)
  * PR 地址：#22
  **注意**：一个 `pull request` 中需要翻译完并提交对应 `Issue` 中指定的所有文件
  ----
  * 翻译时间：6 天
  * 校对时间：2 天
  * 翻译积分：6 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by TobiasLee** [comment]
@leviding 翻译认领

**Comment by pkuwwt** [comment]
低级 翻译成 底层 如何？稍微中性一点

**Comment by pkuwwt** [comment]
还有bias，译者翻译成偏置，没什么问题。只是这个词应该放到词汇表里面去。

**Comment by pkuwwt** [comment]
另外Dense叫成网络层似乎有点绕，不如直接翻成全连接层。
