### ISSUE TITLE
tutorials/eager/eager_basics.ipynb

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow-docs#129]
* Markdown 文件：[eager_basics.ipynb](https://github.com/xitu/tensorflow-docs/blob/zh-hans/tutorials/eager/eager_basics.ipynb)
  * PR 地址：https://github.com/xitu/tensorflow-docs/pull/130
  **注意**：一个 `pull request` 中需要翻译完并提交对应 `Issue` 中指定的所有 MarkDown 文件
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：3-4 分
  * 校对积分：1-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
由 @slyrx 翻译

**Comment by slyrx** [comment]
@leviding 翻译完成

**Comment by leviding** [comment]
@slyrx 收到！
