### ISSUE TITLE
tfx/README.md, tutorials/_index.ipynb and tutorials/eager/automatic_differentiation.ipynb

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow-docs#132]
* Markdown 文件：
    * [x] [tfx/README.md](https://github.com/xitu/tensorflow-docs/blob/zh-hans/tfx/README.md)
    * [x] [tutorials/_index.ipynb](https://github.com/xitu/tensorflow-docs/blob/zh-hans/tutorials/_index.ipynb)
    * [x] [tutorials/eager/automatic_differentiation.ipynb](https://github.com/xitu/tensorflow-docs/blob/zh-hans/tutorials/eager/automatic_differentiation.ipynb)
  * PR 地址：https://github.com/xitu/tensorflow-docs/pull/133
  **注意**：一个 `pull request` 中需要翻译完并提交对应 `Issue` 中指定的所有 MarkDown 文件
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1-2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
由 @slyrx 翻译

**Comment by slyrx** [comment]
@leviding 翻译完成
