### ISSUE TITLE
performance/_toc.yaml and performance/index.md

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow-docs#137]
* Markdown 文件：
    * [x] [performance/_toc.yaml](https://github.com/xitu/tensorflow-docs/blob/zh-hans/performance/_toc.yaml) @slyrx 
    * [x] [performance/index.md](https://github.com/xitu/tensorflow-docs/blob/zh-hans/performance/index.md) @slyrx 
  * PR 地址：https://github.com/xitu/tensorflow-docs/pull/143
  **注意**：一个 `pull request` 中需要翻译完并提交对应 `Issue` 中指定的所有 MarkDown 文件
  ----
  * 翻译时间：3 天
  * 校对时间：1 天
  * 翻译积分：2-3 分
  * 校对积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
由 @slyrx 翻译

**Comment by leviding** [comment]
@slyrx 记得这篇翻译哈

**Comment by slyrx** [comment]
@leviding 👌最近比较忙，耽误了一些，尽快完成

**Comment by slyrx** [comment]
@leviding 翻译完成
