### ISSUE TITLE
tutorials/recurrent_quickdraw.md

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow-docs#14]
* Markdown 文件：[文件地址](https://github.com/xitu/tensorflow-docs/blob/zh-hans/tutorials/recurrent_quickdraw.md)
  * PR 地址：#42
  **注意**：一个 `pull request` 中需要翻译完并提交对应 `Issue` 中指定的所有文件
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4.5 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by TobiasLee** [comment]
@leviding  翻译认领

**Comment by leviding** [comment]
@TobiasLee 赞 👍
