### ISSUE TITLE
html展示格式不对

### ISSUE THREAD

**Issue by billtian** [xitu/tensorflow-docs#146]
在 https://tensorflow.juejin.im/get_started/feature_columns.html 中**分桶列**，**分类标识列**，**分类词汇列**，**哈希列**展示的样式不正确。

![image](https://user-images.githubusercontent.com/3282433/52983191-e52e6200-3424-11e9-8d6e-cd4db3c1524b.png)

**Comment by leviding** [comment]
感谢提出问题，欢迎通过 PR 来提交对文档的优化！

**Comment by leviding** [comment]
文档已优化，详见 https://github.com/xitu/tensorflow-docs/blob/06b54cb4c82a2e875aebbe73d5c37e13e6264ca0/guide/feature_columns.md

感谢指出。
