### ISSUE TITLE
翻译问题

### ISSUE THREAD

**Issue by billtian** [xitu/tensorflow-docs#147]
在 https://tensorflow.juejin.im/get_started/datasets_quickstart.html 中将 'iris_data.load_data()'翻译为**检索虹膜数据**，应该是**加载鸢尾花数据集**

![image](https://user-images.githubusercontent.com/3282433/52983782-aa79f900-3427-11e9-8bf1-559accda1410.png)

ps: 我能怎么方便的参与这个项目，最近正在看这块的文档，有些不合适的是否可以直接提交PR，该项目采用的什么编译的html，我能否在本地直接预览我的修改结果？没有找到这块的介绍，谢谢!

**Comment by leviding** [comment]
@billtian 您好，很高兴收到您的 Issue，欢迎加我微信 517010193，备注一下 TensorFlow 文档。非常欢迎直接通过 PR 来提交对文档的优化！

**Comment by leviding** [comment]
因官方文档更新，本章节已删除，感谢指出。
