### ISSUE TITLE
tutorials/wide.md

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow-docs#16]
* Markdown 文件：[文件地址](https://github.com/xitu/tensorflow-docs/blob/zh-hans/tutorials/wide.md)
  * PR 地址：#20
  **注意**：一个 `pull request` 中需要翻译完并提交对应 `Issue` 中指定的所有文件
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：7.5 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by whatbeg** [comment]
@leviding 翻译认领

**Comment by leviding** [comment]
@whatbeg ok
