### ISSUE TITLE
get_started/checkpoints.md

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow-docs#2]
* Markdown 文件：[文件地址](https://github.com/xitu/tensorflow-docs/blob/zh-hans/get_started/checkpoints.md)
  * PR 地址：
  **注意**：一个 `pull request` 中需要翻译完并提交对应 `Issue` 中指定的所有文件
  ----
  * 翻译时间：4 天
  * 校对时间：1 天
  * 翻译积分：4 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by lsvih** [comment]
认领 @leviding

**Comment by leviding** [comment]
@lsvih ok

**Comment by leviding** [comment]
刚刚发现 pku 老哥把这个翻译完了，那就先关了哈。
