### ISSUE TITLE
mobile/ios_build.md and mobile/tflite/demo_ios.md

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow-docs#24]
* Markdown 文件：
    * [mobile/ios_build.md](https://github.com/xitu/tensorflow-docs/blob/zh-hans/mobile/ios_build.md)
    * [mobile/tflite/demo_ios.md](https://github.com/xitu/tensorflow-docs/blob/zh-hans/mobile/tflite/demo_ios.md)
  * PR 地址：
  **注意**：一个 `pull request` 中需要翻译完并提交对应 `Issue` 中指定的所有文件
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：5 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by changkun** [comment]
@leviding 认领
