### ISSUE TITLE
mobile/prepare_models.md

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow-docs#28]
* Markdown 文件：[文件地址](https://github.com/xitu/tensorflow-docs/blob/zh-hans/mobile/prepare_models.md)
  * PR 地址：#71
  **注意**：一个 `pull request` 中需要翻译完并提交对应 `Issue` 中指定的所有文件
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：7 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by jasonxia23** [comment]
翻译认领 @leviding

**Comment by leviding** [comment]
@jasonxia23 好的呢

**Comment by leviding** [comment]
@jasonxia23 这篇怎么样啦

**Comment by jasonxia23** [comment]
@leviding 抱歉啦，麻烦再等等呢~

**Comment by leviding** [comment]
@jasonxia23 好的，不是很急，好了艾特我

**Comment by jasonxia23** [comment]
@leviding 秒回啊，好呢

**Comment by leviding** [comment]
@jasonxia23 你好，这篇翻译的怎么样了呢

**Comment by leviding** [comment]
@jasonxia23 你好，翻译的怎么样了，现在就差这一个了

**Comment by edvardHua** [comment]
认领

**Comment by leviding** [comment]
@edvardHua ok

**Comment by leviding** [comment]
@edvardHua 翻译的怎么样啦

**Comment by edvardHua** [comment]
好了，对应的 [PR](https://github.com/xitu/tensorflow-docs/pull/71)
