### ISSUE TITLE
mobile/tflite/index.md

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow-docs#29]
* Markdown 文件：[文件地址](https://github.com/xitu/tensorflow-docs/blob/zh-hans/mobile/tflite/index.md)
  * PR 地址：#44
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：5 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by sunhaokk** [comment]
@leviding 翻译认领

**Comment by leviding** [comment]
@sunhaokk ok
