### ISSUE TITLE
TensorFlow V1.7 更新进度及近期规划

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow-docs#31]
> V1.6 与 V1.7 差异详情：[点击查看](https://github.com/xitu/tensorflow-docs/compare/v1.6...v1.7?expand=1)
>
> * 补充版权信息
> * 发布 V1.7 release
> ~* 上线 TensorFlow 中文文档网站（已完成）~
> * 发布 pdf 等形式的中文文档

- [x] install @leviding
- [x] get_started @leviding
- [x] tutorials @changkun
- [x] programmers_guide @JohnJiangLA jiang
- [x] deploy @leviding
- [x] extend @leviding
- [x] performance @leviding
- [x] mobile @leviding
- [x] README @leviding
- ~api_guides~
- ~about~
- ~community~
- ~extras~

| 名称 | 重要性 |
|---|---|
| about | * |
| api_guides | ** |
| community | * |
| deploy | *** |
| extend | *** |
| extras | * |
| get_started | **** |
| install | **** |
| mobile | **** || performance | *** |
| programmers_guide | **** |
| tutorials | **** |

**Comment by leviding** [comment]
@henryatman 网站在建了，这个 issue 的开头不就写了吗

**Comment by wzy816** [comment]
网站是开源项目吗？

**Comment by leviding** [comment]
@有意向一起搞吗，是开源的
