### ISSUE TITLE
请问可否在遵守 Apache License 的情况下，二次更改和发布呢？

### ISSUE THREAD

**Issue by fendouai** [xitu/tensorflow-docs#35]
https://github.com/xitu/tensorflow-docs 

这个项目是 Apache 许可 2.0 ，我能否在保留出处的情况下，放在我的网站上呢。
https://www.apache.org/licenses/LICENSE-2.0.html

同时标注这个项目的版权和TensorFlow 官方的。

**Comment by leviding** [comment]
@fendouai 您好，感谢提出相关问题，现阶段我们的工作重点是文档翻译速度和质量的把控，我们会尽快进行版权相关事项的制定和发布，届时更新到本文档中，谢谢。
