### ISSUE TITLE
get_started/feature_columns.md

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow-docs#5]
* Markdown 文件：[文件地址](https://github.com/xitu/tensorflow-docs/blob/zh-hans/get_started/feature_columns.md)
  * PR 地址：#48
  **注意**：一个 `pull request` 中需要翻译完并提交对应 `Issue` 中指定的所有文件
  ----
  * 翻译时间：8 天
  * 校对时间：2 天
  * 翻译积分：8 分
  * 校对积分：2.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by EmilyQiRabbit** [comment]
@leviding 认领翻译

**Comment by leviding** [comment]
@EmilyQiRabbit 先把之前那个结束吧

**Comment by EmilyQiRabbit** [comment]
@leviding 翻译认领？

**Comment by leviding** [comment]
@EmilyQiRabbit ok

**Comment by EmilyQiRabbit** [comment]
@leviding help wanted 是不是可以去掉了？

**Comment by leviding** [comment]
@EmilyQiRabbit 嗯嗯，是的
