### ISSUE TITLE
/performance/quantization.md

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow-docs#58]
* Markdown 文件：[/performance/quantization.md](https://github.com/xitu/tensorflow-docs/blob/zh-hans/performance/quantization.md)
  * PR 地址：#78
  ----
  * 翻译时间：6 天
  * 校对时间：2 天
  * 翻译积分：6 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by changkun** [comment]
@leviding 认领

**Comment by leviding** [comment]
@changkun 好的呢😘

**Comment by leviding** [comment]
@changkun 翻译的怎么样啦

**Comment by leviding** [comment]
@changkun 翻译的怎么样啦

**Comment by leviding** [comment]
@changkun 翻译的怎么样啦

**Comment by leviding** [comment]
@changkun 怎么样啦老铁 🤣

**Comment by changkun** [comment]
@leviding 我竟无言以对… 这两周真是忙疯了 T_T 我承诺这周内绝对翻出来

**Comment by leviding** [comment]
哈哈哈，好的哈 🤣

**Comment by leviding** [comment]
@changkun 这个怎么样了
