### ISSUE TITLE
/deploy/s3.md and /mobile/tflite/demo_android.md

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow-docs#59]
* Markdown文件：
    * [/deploy/s3.md](https://github.com/xitu/tensorflow-docs/blob/zh-hans/deploy/s3.md)
    * [/mobile/tflite/demo_android.md](https://github.com/xitu/tensorflow-docs/blob/zh-hans/mobile/tflite/demo_android.md)
  * PR 地址：#65
  ----
  * 翻译时间：6 天
  * 校对时间：2 天
  * 翻译积分：6 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by sisibeloved** [comment]
@leviding 翻译认领

**Comment by leviding** [comment]
@sisibeloved ok
