### ISSUE TITLE
get_started/get_started_for_beginners.md

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow-docs#6]
* Markdown 文件：[文件地址](https://github.com/xitu/tensorflow-docs/blob/zh-hans/get_started/get_started_for_beginners.md)
  * PR 地址：#55
  **注意**：一个 `pull request` 中需要翻译完并提交对应 `Issue` 中指定的所有文件
  ----
  * 翻译时间：10 天
  * 校对时间：3 天
  * 翻译积分：10 分
  * 校对积分：3.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by horizon13th** [comment]
@leviding 翻译认领

**Comment by pkuwwt** [comment]
@horizon13th OK

**Comment by leviding** [comment]
@horizon13th 翻译的怎么样啦

**Comment by horizon13th** [comment]
快要完工啦

**Comment by leviding** [comment]
辛苦啦~
