### ISSUE TITLE
/extend/new_data_formats.md

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow-docs#60]
* Markdown 文件：[/extend/new_data_formats.md](https://github.com/xitu/tensorflow-docs/blob/zh-hans/extend/new_data_formats.md)
  * PR 地址：#66
  ----
  * 翻译时间：6 天
  * 校对时间：2 天
  * 翻译积分：6 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by sisibeloved** [comment]
@leviding 翻译认领
