### ISSUE TITLE
/mobile/tflite/devguide.md

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow-docs#61]
* Markdown 文件：[/mobile/tflite/devguide.md](https://github.com/xitu/tensorflow-docs/blob/zh-hans/mobile/tflite/devguide.md)
  * PR 地址：#80
  ----
  * 翻译时间：6 天
  * 校对时间：2 天
  * 翻译积分：6 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by mingxing47** [comment]
翻译认领

**Comment by leviding** [comment]
@mingxing47 ok

**Comment by leviding** [comment]
@mingxing47 翻译的怎么样啦

**Comment by leviding** [comment]
@mingxing47 @edvardHua 翻译的怎么样啦

**Comment by mingxing47** [comment]
不好意思，这几天外出了，这两天内翻译出来~

**Comment by leviding** [comment]
@mingxing47 好的哈

**Comment by leviding** [comment]
@mingxing47 记得这篇哈

**Comment by mingxing47** [comment]
hi, 今天内翻译好提交哈~

**Comment by leviding** [comment]
好的哈

**Comment by leviding** [comment]
@mingxing47 问下，这个有提交吗

**Comment by leviding** [comment]
@mingxing47 这篇怎么样啦

**Comment by mingxing47** [comment]
稍等，我提交

**Comment by leviding** [comment]
您好，提交了吗 @mingxing47 
![image](https://user-images.githubusercontent.com/26959437/40409247-cd2ae06a-5e9c-11e8-87d5-8acb96215a35.png)

**Comment by leviding** [comment]
@mingxing47 提交了吗
