### ISSUE TITLE
/programmers_guide/eager.md

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow-docs#62]
* Markdown 文件：[/programmers_guide/eager.md](https://github.com/xitu/tensorflow-docs/blob/zh-hans/programmers_guide/eager.md)
  * PR 地址：#79
  ----
  * 翻译时间：10 天
  * 校对时间：3 天
  * 翻译积分：10 分
  * 校对积分：3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by Starriers** [comment]
翻译认领

**Comment by leviding** [comment]
@Starriers ok

**Comment by leviding** [comment]
@Starriers 怎么样啦

**Comment by Starriers** [comment]
哇 时间好像是长了点 最迟明天

**Comment by leviding** [comment]
@Starriers 记得这个哈

**Comment by leviding** [comment]
@Starriers 这个怎么样了

**Comment by Starriers** [comment]
翻译好了 忘了提交 我回去就弄
