### ISSUE TITLE
install 文件夹内的内容更新及校对

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow-docs#64]
* [/install/install_linux.md](https://github.com/xitu/tensorflow-docs/blob/zh-hans/install/install_linux.md)
* [/install/install_mac.md](https://github.com/xitu/tensorflow-docs/blob/zh-hans/install/install_mac.md)

将上面两篇译文与下面原文进行详细比较，进行校对修改（包括格式错误/不恰当和翻译错误/不恰当）。修改后，两个文件各提交一个 PR。

* [install_linux.md V1.8 英文原文](https://github.com/xitu/tensorflow-docs/blob/v1.8/install/install_linux.md)
* [install_mac.md V1.8 英文原文](https://github.com/xitu/tensorflow-docs/blob/v1.8/install/install_mac.md)

**Comment by Starriers** [comment]
校对认领 @leviding

**Comment by leviding** [comment]
@Starriers ok

**Comment by leviding** [comment]
@Starriers 怎么样啦

**Comment by Starriers** [comment]
@leviding  今晚之前
