### ISSUE TITLE
/community/benchmarks.md + contributing.md + index.md + groups.md + security.md

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow-docs#67]
* Markdown 文件：
    * [/community/benchmarks.md](https://github.com/xitu/tensorflow-docs/blob/zh-hans/community/benchmarks.md)
    * [/community/contributing.md](https://github.com/xitu/tensorflow-docs/blob/zh-hans/community/contributing.md)
    * [/community/index.md](https://github.com/xitu/tensorflow-docs/blob/zh-hans/community/index.md)
    * [/community/groups.md](https://github.com/xitu/tensorflow-docs/blob/zh-hans/community/groups.md)
    * [/community/security.md](https://github.com/xitu/tensorflow-docs/blob/zh-hans/community/security.md)
  * PR 地址：
  **注意**：一个 `pull request` 中需要翻译完并提交对应 `Issue` 中指定的所有 MarkDown 文件
  ----
  * 翻译时间：7 天
  * 校对时间：2 天
  * 翻译积分：7 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by wzasd** [comment]
翻译认领

**Comment by leviding** [comment]
@wzasd ok
