### ISSUE TITLE
/community/lists.md + roadmap.md + style_guide.md + swift.md

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow-docs#68]
* Markdown 文件：
    * [/community/lists.md](https://github.com/xitu/tensorflow-docs/blob/zh-hans/community/lists.md)
    * [/community/roadmap.md](https://github.com/xitu/tensorflow-docs/blob/zh-hans/community/roadmap.md)
    * [/community/style_guide.md](https://github.com/xitu/tensorflow-docs/blob/zh-hans/community/style_guide.md)
    * [/community/swift.md](https://github.com/xitu/tensorflow-docs/blob/zh-hans/community/swift.md)
  * PR 地址：#76
  **注意**：一个 `pull request` 中需要翻译完并提交对应 `Issue` 中指定的所有 MarkDown 文件
  ----
  * 翻译时间：9 天
  * 校对时间：3 天
  * 翻译积分：9 分
  * 校对积分：3 分 AlenQi 1 分 SpielbergGao 1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@meloalright ok

**Comment by leviding** [comment]
@meloalright 翻译的怎么样啦

**Comment by meloalright** [comment]
@leviding 啊抱歉 我以为是今天才算到期

**Comment by meloalright** [comment]
@leviding 已经翻译完提交PR~

**Comment by leviding** [comment]
@meloalright 是的哈，我就是昨天都提醒了一下，辛苦啦 ❤️
