### ISSUE TITLE
/community/documentation.md

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow-docs#69]
* Markdown 文件：[/community/documentation.md](https://github.com/xitu/tensorflow-docs/blob/zh-hans/community/documentation.md)
  * PR 地址：#77
  **注意**：一个 `pull request` 中需要翻译完并提交对应 `Issue` 中指定的所有 MarkDown 文件
  ----
  * 翻译时间：10 天
  * 校对时间：3 天
  * 翻译积分：8-12 分
  * 校对积分：2-4 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by DAA233** [comment]
@leviding 翻译认领

**Comment by leviding** [comment]
@DAA233 ok

**Comment by DAA233** [comment]
抱歉，我最近因为个人事务突然繁忙，耽搁了翻译进度。明天我会提交翻译结果。

**Comment by leviding** [comment]
@DAA233 好的，辛苦啦
