### ISSUE TITLE
get_started/index.md

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow-docs#7]
* Markdown 文件：[文件地址](https://github.com/xitu/tensorflow-docs/blob/zh-hans/get_started/index.md)
  * PR 地址：#18
  **注意**：一个 `pull request` 中需要翻译完并提交对应 `Issue` 中指定的所有文件
  ----
  * 翻译时间：1 天
  * 翻译积分：1 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
@lsvih

**Comment by lsvih** [comment]
认领 @leviding

**Comment by leviding** [comment]
@lsvih ok
