### ISSUE TITLE
about 文件夹内 4 个 MarkDown 文件

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow-docs#70]
* Markdown 文件：[about 文件夹内 4 个 MarkDown 文件](https://github.com/xitu/tensorflow-docs/tree/zh-hans/about)
  * PR 地址：#75
  **注意**：一个 `pull request` 中需要翻译完并提交对应 `Issue` 中指定的所有 MarkDown 文件
  ----
  * 翻译时间：5 天
  * 校对时间：2 天
  * 翻译积分：5 分
  * 校对积分：2 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by wzasd** [comment]
翻译认领 @leviding

**Comment by leviding** [comment]
@wzasd 好的，这个翻译的时候，源 MarkDown 有的地方格式有问题，例如加粗无法解析等，翻译的时候麻烦也调整下哈
