### ISSUE TITLE
get_started/premade_estimators.md

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow-docs#8]
* Markdown 文件：[文件地址](https://github.com/xitu/tensorflow-docs/blob/7ffc9e517dac3fcb50e74adaba0bf63584ef5e6b/get_started/premade_estimators.md)
  * PR 地址：#46
  **注意**：一个 `pull request` 中需要翻译完并提交对应 `Issue` 中指定的所有文件
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：5 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by CACppuccino** [comment]
翻译认领 @leviding 另外，图好像丢了一个

**Comment by leviding** [comment]
@CACppuccino 是有丢图情况，翻译的时候去官方找一下吧，这边有 image 文件夹
