### ISSUE TITLE
performance/datasets_performance.md

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow-docs#9]
* Markdown 文件：[文件地址](https://github.com/xitu/tensorflow-docs/blob/zh-hans/performance/datasets_performance.md)
  * PR 地址：#54
  **注意**：一个 `pull request` 中需要翻译完并提交对应 `Issue` 中指定的所有文件
  ----
  * 翻译时间：9 天
  * 校对时间：3 天
  * 翻译积分：9 分
  * 校对积分：3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by mrcangye** [comment]
@leviding  认领翻译

**Comment by mrcangye** [comment]
认领翻译

**Comment by leviding** [comment]
@mrcangye ok

**Comment by mrcangye** [comment]
翻译完成 @leviding
