### ISSUE TITLE
performance/xla/jit.md 完善，只需翻译一行文字。

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow-docs#94]
![image](https://user-images.githubusercontent.com/26959437/46581457-aac2ba80-ca6b-11e8-8f3a-c357396e76c8.png)

将第 13 行翻译完善并 PR

* 文件地址：https://github.com/xitu/tensorflow-docs/blob/zh-hans/performance/xla/jit.md
* PR 地址：https://github.com/xitu/tensorflow-docs/pull/100

**Comment by zhusimaji** [comment]
@leviding 翻译认领，看着一行。。。

**Comment by leviding** [comment]
@zhusimaji Great
