### ISSUE TITLE
community/documentation.md

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow-docs#95]
* Markdown 文件：[community/documentation.md](https://github.com/xitu/tensorflow-docs/blob/zh-hans/community/documentation.md)
  * commit：https://github.com/xitu/tensorflow-docs/commit/82ad89104aeaff016ad63d7c1ee13a2742d90cb0
  ----
  * 翻译时间：6 天
  * 校对时间：2 天
  * 翻译积分：6 分
  * 校对积分：2-3 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
由 @lsvih 翻译

**Comment by leviding** [comment]
@lsvih 翻译的时候可以参考 https://github.com/xitu/tensorflow-docs/commit/19efcc66d187350dbab8ec96cc63d2e673dfab0c
这个 commit 记录，这是将本文件更新到 v1.10 时的 commit 记录，因为 diff 过于繁琐，所以用新版本的英文内容覆盖了原来的翻译，你通过这个 commit 可以看到，有不少内容是之前翻译过的，可以参考（仅供参考）。

例如下图：

![image](https://user-images.githubusercontent.com/26959437/46589325-f82a4080-cada-11e8-92d5-51b586a6f3d1.png)

**Comment by lsvih** [comment]
好的

**Comment by lsvih** [comment]
:( 因故要晚一天，明天提交

**Comment by leviding** [comment]
好，不急

**Comment by lsvih** [comment]
@leviding 不小心直接提交了，commit 82ad891

**Comment by leviding** [comment]
@lsvih 好的，可以。
